### ISSUE TITLE
HttpLinkServerException

### ISSUE THREAD

**Issue by manuelduarte077** [baconcheese113/graphql_codegen_example#1]
Hello, I was seeing your conversation with the creator of graphql_codegen, then I came to review the example that I created using the package, and I get this error

![Screen Shot 2022-07-25 at 09 45 27](https://user-images.githubusercontent.com/46093689/180828500-bffae970-39fc-414b-8808-b505b3ddd245.png)

**Comment by manuelduarte077** [comment]
I tried to understand the error, to know what was happening, I tried some things like after queries of the api, but the doubt followed me that why he wants it from lauch, that's where it came out

  <img height="250em" src="https://user-images.githubusercontent.com/46093689/180837828-174c8752-fde5-4194-862e-e85a4618c1fc.png"/>

  <img height="250em" src="https://user-images.githubusercontent.com/46093689/180837889-ef26a6a2-12c4-40bb-8f03-2fdfc7127203.png"/>

**Comment by baconcheese113** [comment]
This is due to a setting of the public graph api that I'm using, it limits the number of fields you can use in a single query

I'm assuming you added more fields to query?

**Comment by manuelduarte077** [comment]
Yes

can that be then

**Comment by baconcheese113** [comment]
You would have to remove fields from the query, or break it into multiple queries. It's a limitation of the public backend

**Comment by baconcheese113** [comment]
I just checked the repo again and realized that they have further reduced the permissible complexity. I removed some unnecessary parts and it should be functioning again
